name: chat_app

services:
    cache:
        image: redis:latest
        container_name: cache
        ports:
            - "6380:6379"
        networks:
            - net

networks:
    net:
        driver: bridge
